### PR TITLE
Verify rangeFromLineNumber inputs

### LINKED ISSUE #59: Further check rangeFromLineNumber parameters
Currently being triggered by the following steps in `linter-eslint`, but stopping it here will fix anywhere else that this is causing crashes on:

1. Try to run `linter-eslint` with a module missing ("parser `babel-eslint` requested but not installed
2. Get a response from the linter of:
```json
{
  "message": "Cannot find module 'babel-eslint'",
  "line": 0,
  "column": 0,
  "severity": 2
}
```
3\. `Helpers.rangeFromLineNumber(textEditor, line - 1)` is then called, meaning `rangeFromLineNumber` is being called with a line of `-1`.

So, tl;dr: Verify that `lineNumber` and `colStart` are within the valid range for a line before attempting to call Atom functions.

### PR DESCRIPTION
**Pull request by Arcanemagus**
Verify that lineNumber and colStart are numbers with values of at least 0.

Fixes #59.

### CODE REVIEW

File: lib/helpers.coffee [hunk 1]
```diff
@@ -58,11 +58,11 @@ module.exports = Helpers =
 
   rangeFromLineNumber: (textEditor, lineNumber, colStart) ->
     throw new Error('Provided text editor is invalid') unless textEditor?.getText?
-    if typeof lineNumber is 'undefined' or lineNumber isnt lineNumber
+    if typeof lineNumber isnt 'number' or lineNumber isnt lineNumber or lineNumber < 0
       return [[0, 0], [0, 1]]
     lineLength = textEditor.getBuffer().lineLengthForRow(lineNumber)
     throw new Error('Column start greater than line length') if colStart > lineLength
-    unless typeof colStart is 'number'
+    unless typeof colStart is 'number' and not (colStart < 0)
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: Definitely cleaner that way.

File: lib/helpers.coffee [hunk 2]
```diff
@@ -159,7 +159,7 @@ module.exports = Helpers =
     unless names instanceof Array
       names = [names]
     startDir = startDir.split(path.sep)
-    while startDir.length && startDir.join(path.sep)
+    while startDir.length and startDir.join(path.sep)
```
Comment (Arcanemagus) [inline lib/helpers.coffee]: Looks like this broke the tests: https://travis-ci.org/AtomLinter/atom-linter/builds/91920981

Comment (Arcanemagus) [inline lib/helpers.coffee]: Added it back in.
