### PR TITLE
Handle mixed indentation

### LINKED ISSUE #63: re: Check if column start is greater than line length
I'm currently getting
```
Error: Column start (11) greater than line length(8)
at Object.module.exports.Helpers.rangeFromLineNumber
lib/Helpers.coffee:73:17
```
while running atom-linter@3.3.7

related to pull request #53 ?

### PR DESCRIPTION
**Pull request by Arcanemagus**
Previously it was assumed that a file had consistent indentation, this fixes that incorrect assumption.

Fixes #63.

### CODE REVIEW

File: lib/helpers.coffee [hunk 1]
```diff
@@ -48,7 +48,8 @@ module.exports = Helpers =
         return reject(error) if error and error.code is 'ENOENT'
         handle()
         if error.code is 'EACCES'
-          error = new Error("Failed to spawn command `#{command}`. Make sure it's a file, not a directory and it's executable.")
+          error = new Error("Failed to spawn command `#{command}`. Make sure " +
```
Comment (steelbrain) [inline lib/helpers.coffee]: The last one was cleaner IMO

File: lib/helpers.coffee [hunk 2]
```diff
@@ -65,9 +66,11 @@ module.exports = Helpers =
     if lineNumber > maxLine
       throw new Error("Line number (#{lineNumber}) greater than maximum line (#{maxLine})")
     if typeof colStart isnt 'number' or colStart < 0
-      colStart = (textEditor.indentationForBufferRow(lineNumber) * textEditor.getTabLength())
-      if colStart isnt 0
-        colStart -= 1
+      indentation = buffer.lineForRow(lineNumber).match(/^\s+/)
+      if indentation? and indentation.length = 1
```
Comment (steelbrain) [inline lib/helpers.coffee]: `indentation?` <-- you dont need the `?` here because if it's null, it'll be falsy already

File: lib/helpers.coffee (hunk 1 above)
Comment (Arcanemagus) [inline lib/helpers.coffee]: It's also a very long line, do you want it split in another section? (after the period?)

Comment (steelbrain) [inline lib/helpers.coffee]: Do we really have to split it? :stuck_out_tongue:

**Comment by steelbrain** [comment]
Just some minor nits, after that LGTM

File: lib/helpers.coffee (hunk 1 above)
Comment (Arcanemagus) [inline lib/helpers.coffee]: Well it's a warning with CoffeeLint, but we don't _need_ to split it I suppose.

**Comment by steelbrain** [comment]
Merge at will
